/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg_1.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msg_1.pb-c.h"
void   msg_1__init
                     (Msg1         *message)
{
  static const Msg1 init_value = MSG_1__INIT;
  *message = init_value;
}
size_t msg_1__get_packed_size
                     (const Msg1 *message)
{
  assert(message->base.descriptor == &msg_1__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t msg_1__pack
                     (const Msg1 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &msg_1__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t msg_1__pack_to_buffer
                     (const Msg1 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &msg_1__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Msg1 *
       msg_1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Msg1 *)
     protobuf_c_message_unpack (&msg_1__descriptor,
                                allocator, len, data);
}
void   msg_1__free_unpacked
                     (Msg1 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &msg_1__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor msg_1__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg1, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Msg1, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "socre",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Msg1, socre),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned msg_1__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = name */
  2,   /* field[2] = socre */
};
static const ProtobufCIntRange msg_1__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor msg_1__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "msg_1",
  "Msg1",
  "Msg1",
  "",
  sizeof(Msg1),
  3,
  msg_1__field_descriptors,
  msg_1__field_indices_by_name,
  1,  msg_1__number_ranges,
  (ProtobufCMessageInit) msg_1__init,
  NULL,NULL,NULL    /* reserved[123] */
};
